# NumPy

In [1]:
import numpy as np

### Одномерный массив

In [2]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
V = np.array([3.4, 6.9, 99.8, 12.8])
print("F: ", F)
print("V: ", V)
print("Type of F: ", F.dtype)
print("Type of V: ", V.dtype)
print("Dimension of F: ", np.ndim(F))
print("Dimension of V: ", np.ndim(V))
print("Size: {}, bytes: {}, shape: {}, dtype: {}".format(F.size, F.nbytes, F.shape, F.dtype))

F:  [ 1  1  2  3  5  8 13 21]
V:  [ 3.4  6.9 99.8 12.8]
Type of F:  int32
Type of V:  float64
Dimension of F:  1
Dimension of V:  1
Size: 8, bytes: 32, shape: (8,), dtype: int32


### Многомерный массив

In [3]:
A = np.array([[3.4, 8.7, 9.9], 
              [1.1, -7.8, -0.7],
              [4.1, 12.3, 4.8]])
print(A)
print(A.ndim)

B = np.array([[[111, 112], [121, 122]],
              [[211, 212], [221, 222]],
              [[311, 312], [321, 322]]])
print(B)
print(B.ndim)

[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]]
2
[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
3


### arange

In [4]:
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x)    # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)
x = np.arange(0.5, 10.4, 0.8, int)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


### linspace

In [5]:
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


### shape

In [6]:
x = np.array([ [67, 63, 87],
               [77, 69, 59],
               [85, 87, 99],
               [79, 72, 71],
               [63, 89, 93],
               [68, 92, 78]])
print(x.shape)

x.shape = (3, 6)
print(x)

x.shape = (2, 9)
print(x)

B = np.array([[[111, 112], [121, 122]],
              [[211, 212], [221, 222]],
              [[311, 312], [321, 322]]])
print(B.shape)

(6, 3)
[[67 63 87 77 69 59]
 [85 87 99 79 72 71]
 [63 89 93 68 92 78]]
[[67 63 87 77 69 59 85 87 99]
 [79 72 71 63 89 93 68 92 78]]
(3, 2, 2)


### indexing

In [7]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
# print the first element of F, i.e. the element with the index 0
print(F[0])
# print the last element of F
print(F[-1])
B = np.array([[[111, 112], [121, 122]],
              [[211, 212], [221, 222]],
              [[311, 312], [321, 322]]])
print(B[0])
print(B[0][1])
print(B[0][1][0])
# More efficient, because do not create temporary copy of intermediate arrays
print(B[0, 1])
print(B[0, 1, 0])

1
21
[[111 112]
 [121 122]]
[121 122]
121
[121 122]
121


### slicing

In [8]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(S[2:5])
print(S[:4])
print(S[6:])
print(S[:])

[2 3 4]
[0 1 2 3]
[6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A[:3,2:])
print(A[3:,:])
print(A[:,4:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]
[[41 42 43 44 45]
 [51 52 53 54 55]]
[[15]
 [25]
 [35]
 [45]
 [55]]


In [10]:
X = np.arange(28).reshape(4,7)
print(X)

print(X[::2, ::3])

print(X[::, ::3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
[[ 0  3  6]
 [14 17 20]]
[[ 0  3  6]
 [ 7 10 13]
 [14 17 20]
 [21 24 27]]


In [11]:
# Slice of numpy.ndarray creates a view of original ndarray
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
S = A[2:6]
S[0] = 22
S[1] = 23
print(A)

# Slice of list creates a copy
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
lst2 = lst[2:6]
lst2[0] = 22
lst2[1] = 23
print(lst)

[ 0  1 22 23  4  5  6  7  8  9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### ones, zeros, identity, diag

In [12]:
E = np.ones((2,3))
print(E)

F = np.ones((3,4),dtype=int)
print(F)

Z = np.zeros((2,4))
print(Z)

print(np.identity(4))

print(np.diag([1, 2, 3], k=1))

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


### Element-wise operations

In [13]:
lst = [2, 3, 7.9, 3.3, 6.9, 0.11, 3, 10.3, 12.9]
v = np.array(lst)
v = v + 2
print(v)
print(v * 2.2)
print(v ** 1.5)
print(np.unique(v))

[ 4.    5.    9.9   5.3   8.9   2.11  5.   12.3  14.9 ]
[ 8.8   11.    21.78  11.66  19.58   4.642 11.    27.06  32.78 ]
[ 8.         11.18033989 31.14962279 12.2015163  26.55125232  3.06495204
 11.18033989 43.13776768 57.51477202]
[ 2.11  4.    5.    5.3   8.9   9.9  12.3  14.9 ]


In [14]:
A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
B = np.ones((3, 3))
print("Adding to arrays: ")
print(A + B)
print("\nMultiplying two arrays: ")
print(A * (B + 1))

Adding to arrays: 
[[12. 13. 14.]
 [22. 23. 24.]
 [32. 33. 34.]]

Multiplying two arrays: 
[[22. 24. 26.]
 [42. 44. 46.]
 [62. 64. 66.]]


In [15]:
M = 0.5 * np.diag(np.ones(3))
print(np.linalg.inv(M))

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


### Execution time and aggregation

In [16]:
v = np.random.randint(0, 100, 1000)
%timeit v + 1

lst = list(v)
%timeit [val + 2 for val in lst]

1.79 µs ± 119 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
228 µs ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
from numpy import random
data = [random.random() for _ in range(1000000)]
%timeit min(data)

23.4 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
np_data = np.array(data)
%timeit np.min(np_data)

832 µs ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
count = int(1e7)
a, b = [random.random() for _ in range(count)], [random.random() for _ in range(count)]

%timeit [i+j for (i, j) in zip(a, b)]

1.04 s ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
a, b = np.array(a), np.array(b)
%timeit a + b

43.8 ms ± 606 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
def slow():
    a = range(10000)
    return [i ** 2 for i in a]

%timeit slow()

3.04 ms ± 207 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
def fast():
    a = np.arange(10000)
    return a ** 2

%timeit fast()

12.6 µs ± 471 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Matrix multiplication

In [23]:
A = np.array([ [1, 2, 3], 
               [3, 2, 1] ])
B = np.array([ [2, 3, 4, -2], 
               [1, -1, 2, 3],
               [1, 2, 3, 0] ])
# es muss gelten:
print(A.shape[-1] == B.shape[-2], A.shape[1]) 
print(np.dot(A, B))

True 3
[[ 7  7 17  4]
 [ 9  9 19  0]]


### Broadcasting

In [24]:
A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
B = np.array([1, 2, 3])
print("Multiplication with broadcasting: ")
print(A * B)
print("... and now addition with broadcasting: ")
print(A + B)

Multiplication with broadcasting: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition with broadcasting: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


<img src="https://i.imgur.com/Ja6Y68s.png">

In [25]:
A * B[:, np.newaxis]

array([[11, 12, 13],
       [42, 44, 46],
       [93, 96, 99]])

<img src="https://i.imgur.com/G5Zqe29.png">

### Dimensions

In [26]:
A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])
flattened_A = A.flatten()
print(flattened_A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [27]:
X = np.array(range(24))
Y = X.reshape((3, 4, 2))
Y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [28]:
x = np.array([2, 5, 18, 11, 4])
y = x[:, np.newaxis]
print(y)

[[ 2]
 [ 5]
 [18]
 [11]
 [ 4]]


In [29]:
A = np.array([3, 4, 5])
B = np.array([1, 9, 0])
print(np.row_stack((A, B)))
print(np.column_stack((A, B)))
np.shape(A)

[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]


(3,)

In [30]:
v = np.array([1, 3, 7])

x = np.vstack((v, v))
print(x, x.shape)

y = np.hstack((v, v))
print(y, y.shape)

z = np.stack((v, v))
print(z, z.shape)

[[1 3 7]
 [1 3 7]] (2, 3)
[1 3 7 1 3 7] (6,)
[[1 3 7]
 [1 3 7]] (2, 3)


### Advanced indexing and masking

In [31]:
M = np.arange(12).reshape(-1, 3)
M

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
M[1:3, -2:]

array([[4, 5],
       [7, 8]])

In [33]:
M[:, 0]
M[::2, 0]
M[1::2, 0]

array([3, 9])

In [34]:
M[[0, 2, 3], :]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
mask = (M % 2 == 0)
mask

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [36]:
indices = np.where(mask)
indices

(array([0, 0, 1, 2, 2, 3], dtype=int32),
 array([0, 2, 1, 0, 2, 1], dtype=int32))

In [37]:
M[indices[0], indices[1]]

M[M % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [38]:
C = np.array([123, 188, 190, 99, 77, 88, 100])
A = np.array([4, 7, 2, 8, 6, 9, 5])
R = C[A <= 5]
print(R)

C[[0, 2, 3, 1, 4, 1]]

[123 190 100]


array([123, 190,  99, 188,  77, 188])

### Vectorized operations

In [39]:
def vector_mul(k, x):
    # x is some vector
    return x * k

vectorized = np.vectorize(vector_mul, excluded=['x'], otypes=[np.ndarray])
vectorized(k=np.array([1, 3]), x=np.arange(3))

array([array([0, 1, 2]), array([0, 3, 6])], dtype=object)